### ISSUE TITLE
rebar3 lfe compile fails when using (include-lib)

### ISSUE THREAD

**Issue by cmkarlsson** [lfe-rebar3/compile#13]
Running `rebar3 lfe compile` as standalone fails if you include libraries from dependecies.

How to reproduce

``` console
$ rebar3 version
rebar 3.0.0+build.272.ref7d29b74 on Erlang/OTP 18 Erts 7.2
$ rebar3 new lib includebug
$ cd includebug
$ rm src/includebug.erl
$ cat rebar.config                                                               
{erl_opts, [debug_info]}.
{deps, [
    {exemplar, {git, "git@github.com:lfex/exemplar.git", {branch, "master"}}}
]}.

{provider_hooks, [
  {post, [{compile, {lfe, compile}}]}
 ]}.

{plugins, [
  {'lfe-compile',
    {git, "https://github.com/lfe-rebar3/compile.git", {tag, "0.3.0"}}}
]}.
$ cat src/includebug.lfe
(defmodule includebug
  (export (one 1)))

(include-lib "exemplar/include/html-macros.lfe")

(defun one (x) (+ 1 x))
$ rebar3 lfe compile
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
```

Error is:

``` erlang
{4,lfe_macro,
                                  {expand_macro,
                                   ['include-lib',
                                    "exemplar/include/html-macros.lfe"],
                                   badarg}}]}
```

Compiling with `rebar3 compile` works.

**Comment by cmkarlsson** [comment]
The problem is that the dependencies are not added to the code path using only the `rebar3 lfe compile` command.

**Comment by cmkarlsson** [comment]
Exploring this shows more problems with `rebar3 lfe compile`. It doesn't seem to compile dependencies. Adding the path to dependencies is easy but compiling them? What if some of the dependencies are non lfe? How will `rebar3 lfe compile` plugin handle them?

**Comment by yurrriq** [comment]
I think the general idea is to include `lfe-compile` as a post-`compile` hook (as above) and call `rebar3 compile` instead of just `rebar3 lfe compile`. It could be cool to update `lfe compile` to be standalone, but I think until we have a bigger LFE ecosystem, it'll be hard to avoid needing to compile Erlang dependencies too, in which case `rebar3 compile` with the post-hook makes more sense to me.

**Comment by yurrriq** [comment]
Just ran into a similar problem. It seems `lfe compile` (as a `compile` `pre` hook) is not copying the `include` dirs so `include-lib` can fail when there's no appropriate `include` dir in `_build`. A quick hack is to `s/pre/post/` but some (or all?) of the documentation out there, including the [blog post](http://blog.lfe.io/tutorials/2016/03/25/0858-lfe-and-rebar3/), suggests `pre`, which makes this a real problem. Thoughts, @oubiwann, @cmkarlsson?

**Comment by cmkarlsson** [comment]
I've been running it as a post hook for a while and it seems to be working well. As a more general comment in which direction lfe compile should go it depends on resources. Being able to run lfe compile completely stand-alone (or as a pre-hook) will require lots of work which rebar3 already solves.

Are there any drawbacks to running it as a post hook? The only thing I can think of is if some erlang libraries relies on lfe libraries which I don't think will be the case for a while?

**Comment by yurrriq** [comment]
> I've been running it as a post hook for a while and it seems to be working well.

Good to hear. Same here. I think we should update as many docs as we can to suggest `post` instead of `pre`.

> ... will require lots of work which rebar3 already solves

Agreed. I think we should let `rebar3` do it's thing, and have `lfe-compile` only do as its name suggests.

> The only thing I can think of is if some erlang libraries relies on lfe libraries

I think even that should be fine, right?

Perhaps in the tradition of great error messages à la Elm we could add a suggestion to set it as a `post` hook if we detect `{lfe,compile}` as a `pre` hook in the event of a compilation failure.

**Comment by cmkarlsson** [comment]
> Perhaps in the tradition of great error messages à la Elm we could add a suggest to set it as a post hook if we detect {lfe,compile} as a pre hook in the event of a compilation failure.

Yes, that is a good idea. Elm error messages have been very helpful to quickly learn the language and it definately would help people get up to speed with lfe.

**Comment by yurrriq** [comment]
Closing this, for now anyway, since the README says to use a `post`-hook and there's not a clear path forward here.
