### ISSUE TITLE
Apps in apps/* are ignored

### ISSUE THREAD

**Issue by timclassic** [lfe-rebar3/compile#2]
I attempted to use lfe-compile with some LFE source located under apps/\* instead of directly in src/.  It does not appear to know how to look here.  I started trying to add support, but then ran into the problems described in Issue #1.

**Comment by oubiwann** [comment]
Yup, you're absolutely correct. `./apps` was completely overlooked. On it.

**Comment by oubiwann** [comment]
Heads up:
- I've moved the project to a new org and shorter name: https://github.com/lfe-rebar3/compile
- I've merged all the work from #1 into master

Note that the old links and github origins will still work (Github supports redirects, etc.). I wanted to mention this in case you looked for it in the lfex github org and couldn't find it.

**Comment by yurrriq** [comment]
Is this working now? Otherwise I could take a look.

**Edit**: This seems to be working and I think the issue can be closed.

**Comment by oubiwann** [comment]
I _think_ it's working; if you could confirm (or deny!), then we could (hopefully) close this ticket ...

**Comment by yurrriq** [comment]
I've got a project structured with `apps/` and it seems to work :confused:. The compilation failed when I tried earlier today, but I think it had more to do with my improper `{i, ...}` config, or lack thereof. It definitely tried to compile `apps/*/{src,test}/*` though. I'll try again with proper config and report back.

**Comment by yurrriq** [comment]
I can't seem to figure out the `{i, ...}` config.. I've got `apps/a` that calls `(include-lib "b/include/header.hrl")` and it can't seem to find it.. Where `header.hrl` lives in `apps/b/include/`.

**Comment by timclassic** [comment]
I re-ran my original testing for building .lfe files in apps/*/src/ and it appears to work out-of-the-box in the latest version of this plugin.  Judging by the @oubiwann's comments in #1, there has already been much more extensive testing than my trivial compile+run test.  However, @yurrriq's comments above reminded me to test and post my results, so here they are!

From my perspective this bug may be closed.  @oubiwann, thank you for the great work.  I hope to use LFE soon for a (yet-undefined) new project.  I'm sure I'll have a much better set of tests then.

Shall I close this issue?

**Comment by yurrriq** [comment]
Sounds good to me. My issue is totally unrelated to `rebar3 lfe compile`.

**Comment by timclassic** [comment]
Okay, I'll close.  Thanks, all.
