### ISSUE TITLE
Uncaught error when exporting undefined function

### ISSUE THREAD

**Issue by yurrriq** [lfe-rebar3/compile#21]
When you try to use `lfe-rebar3` to compile an LFE module that tries to export undefined functions, it crashes `rebar3`. This means ~~we're not [matching the resulting error pattern](https://github.com/lfe-rebar3/compile/blob/master/src/lr3_comp.erl#L26-L35)~~ there ~~is~~ was a bug in `rebar3`.
### Environment

| Name | Version |
| --- | --- |
| macOS | 10.11.5 |
| erlang | 18.3.4 |
| lfe | 1.1.1 |
| rebar3 | 3.2.0 |
### Minimum Failing Example

<details>
  <summary>

rebar.config</summary>

``` erlang
%% -*- erlang -*-

{plugins, [
  {'lfe-compile',
   {git, "git://github.com/lfe-rebar3/compile.git",
    {tag, "0.4.0"}}}
]}.

{provider_hooks, [{pre, [{compile, {lfe, compile}}]}]}.

{overrides, [
  {override, 'lfe-compile', [
    {deps, [{lfe, {git, "git://github.com/rvirding/lfe.git", {tag, "1.1.1"}}}]}
  ]}
]}.
```

</details>

<details>
  <summary>

src/example.app.src</summary>

``` erlang
{application,example,[{vsn,"0.0.0"}]}.
```

</details>

<details>
  <summary>

src/example.lfe</summary>

``` lfe
(defmodule example (export (nothing 0)))
```

</details>

<details>
  <summary>

Compile results</summary>

``` erlang
{error,
 [{error,
   [{"/path/to/src/example.lfe",
     [{9999,lfe_lint,
       {unbound_func,{nothing,0}}}]}],
   []}],
 [],[]}
```

**Comment by yurrriq** [comment]
Related: #15, #11

**Comment by cmkarlsson** [comment]
As disussed on #erlang-lisp , this may be a rebar3 bug introduced sometime after rebar3 3.1.0

rebar3 tries to use the passed in Config as both a dict and a list. So no matter which type we pass in one of them will fail.

Half-confirmed in #rebar

**Comment by cmkarlsson** [comment]
Haven't had time to report to rebar and not 100% sure they are at fault as it may be our use of rebar that is not ideal.  I'm not able to do anything on this for at least a week and in a rush to go so attaching a patch to lr3_comp.erl which works around the problem if someone wants to have a look.

The patch works with both rebar 3.1.0 and rebar 3.2.0 (and likely any rebar > 3.0.0)

[patch-bug-21.diff.txt](https://github.com/lfe-rebar3/compile/files/375113/patch-bug-21.diff.txt)

**Comment by yurrriq** [comment]
erlang/rebar3#1280 has been merged, so we should test with that.

**Comment by yurrriq** [comment]
With [0.6.0](https://github.com/lfe-rebar3/compile/releases/tag/0.6.0):

```
$ rebar3 compile
===> Verifying dependencies...
 ~~>    Finding .lfe files ...
 ~~>    Compiling ./src/example.lfe ...
===> Compiling apps/dojo_store/src/example.lfe failed
/path/to/src/example.lfe:9999: unbound function: #(nothing 0)
```

:+1:

**Comment by yurrriq** [comment]
Also note that you can do this now, since I've published 0.6.0 to Hex:

``` erlang
{plugins, [
  {'lfe-compile', "0.6.0", {pkg, rebar3_lfe_compile}}
]}.
```

The `git` version will work fine too.

``` erlang
{plugins, [
  {'lfe-compile',
   {git, "git://github.com/lfe-rebar3/compile.git",
    {tag, "0.6.0"}}}
]}.
```

**Comment by oubiwann** [comment]
This change seems to remove `erl_opts` ... is my reading of the diff correct? It seems that only the `lfe_opts` are now used to build the config data ...

I'll keep looking in case I've misread, but re-opening for now.

**Comment by oubiwann** [comment]
Ah, I see - it's done further down, in a different file now.

Re-closing.
