### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by yurrriq** [lfe-rebar3/compile#23]
I would imagine we can add `rebar3` as a `test` dependency and take cues from [rebar_compile_SUITE](https://github.com/erlang/rebar3/blob/master/test/rebar_compile_SUITE.erl). We should make sure to cover some of the bad error cases that have come up.

Once erlang/rebar3#1331 gets sorted, we should ensure `test/*.lfe` get compiled and the `.beam` files end up in the right place.

We should also test a multi-module `.lfe` file and make sure that works correctly. I don't do this personally, but `lfe-compile` needs to handle it.

**Comment by yurrriq** [comment]
It may also behoove us test a few versions of `rebar3`, if that's practical, maybe via different `profiles`. Either way we should mention the supported version(s) in `README.md`.

**Comment by oubiwann** [comment]
Created tickets for this in new project.
