### ISSUE TITLE
Make user 'oubiwann' the Hex.pm maintainer

### ISSUE THREAD

**Issue by oubiwann** [lfe-rebar3/compile#25]
@yurrriq: I've finally added myself to hex.pm; can you make me the owner now?

Thanks!

**Comment by yurrriq** [comment]
Will do. Not sure I can remove myself, but I won't publish unless we've discussed it.

**Comment by yurrriq** [comment]
Done. I've removed myself as well.

For posterity:

``` fish
rebar3 hex owner add rebar3_lfe_compile <your email>
rebar3 hex owner remove rebar3_lfe_compile <my email>
```

**Comment by oubiwann** [comment]
Thanks!
