### ISSUE TITLE
post compile hook and {vsn, git} in .app.src file => relx release not generated

### ISSUE THREAD

**Issue by amitizle** [lfe-rebar3/compile#29]
I'm not sure if this is related to this specific provider or to the _rebar3_ behaviour in general, as I didn't investigate it yet. However I'm posting in here since you might have an idea what this is related to.

I have got an LFE application that is built with _rebar3_ and this plugin.
It's all working perfectly fine. However, when I'm using a combination of `{vsn, git}` in the `<app>.app.src` file AND running this provider as a *post compile* hook, the `git` version is not translated to the git tag. Also the generated `.app` file remains with `{vsn, git}`.

When I'm changing the hook to run *pre compile*, everything is generated correctly while creating a _relx_ release.

I assume this is related to _rebar3_ rather than _lfe-compile_ plugin.
I thought it's worth mentioning it here anyway (and the fact that changing to `pre` helps).

EDIT: adding versions I have tested the above with:

```
lfe-compile: 0.7.0, 0.8.0-rc3
rebar3: 3.3.2, 3.3.3
```

**Comment by amitizle** [comment]
I finally got the time to take a look and saw that the first step in `compile_normal_apps` is to copy the `.app.src` file to `.app` file.
This is done without resolving the app version (i.e. `{vsn, git}`).

I took a further look on how it's done in [`rebar3`](https://github.com/erlang/rebar3/blob/master/src/rebar_otp_app.erl#L113) and there it's initially resolving the `Vsn` (`app_vsn`) and only then writing the `.app` file with the resolved `vsn`.

I guess this can be left that way, but I am wondering why this is done in the plugin?
Also, if so, maybe it's worth adding resolving for the `Vsn` before copying?

**Comment by yurrriq** [comment]
@amitizle, you might like to try my WIP simpler [rebar_prv_lfe](https://github.com/yurrriq/rebar_prv_lfe). I tried to keep it as simple as possible and avoid duplicating efforts in rebar3's compile provider.

**Comment by amitizle** [comment]
Will give it a shot @yurrriq , thanks!

**Comment by oubiwann** [comment]
The new LFE rebar3 plugin will be implementing full release support, as this is going to be what we recommend going forward for LFE applications deployed into production.

Here are the release tickets:
* https://github.com/lfe-rebar3/rebar3_lfe/issues/1
* https://github.com/lfe-rebar3/rebar3_lfe/issues/6

I've added a ticket to ensure that `rebar3 lfe compile` does the proper thing with `vsn`.
