### ISSUE TITLE
Add support for module hierarchies

### ISSUE THREAD

**Issue by oubiwann** [lfe-rebar3/compile#4]
Note that this is not true package support, since Erlang/LFE don't have such a concept.

Instead, this is about finding modules in a directory structure and creating a beam file name that is composed of the path elements of the module files parent directories.

This will mean that you can have a path structure like `src/a/b/c/d.lfe` and, once compiled, there would be a `.beam` file in `./ebin` created with the name `a.b.c.d.beam`. Calling this module's functions from LFE code would be done in the usual manner: `(a.b.c.d:some-func ...)`. The onus will of course be on the developer to ensure that the module is given the proper name: `(defmodule a.b.c.d ...)`.

**Comment by yurrriq** [comment]
I don't think I would ever use such a feature and it seems like this would get messy w.r.t. multi-module `.lfe` files. Is this still something you want, @oubiwann, @jjl?

**Comment by oubiwann** [comment]
So it turns out this is exactly what the Clojerl project has done. It's not actually messy at all: it's just flattening a directory structure into a `.beam` file with a dotted name.

I'm closing down this repo, though, and will move this feature request to the new LFE plugin project ...
