### ISSUE TITLE
Tag 0.3.0

### ISSUE THREAD

**Issue by yurrriq** [lfe-rebar3/compile#9]
I don't have permissions, so I can't do it. Maybe you could add me, @oubiwann :grin:

N.B. here's a [hack](https://www.rebar3.org/docs/configuration#overrides) I'm using in the mean time:

``` erlang
{overrides,
 [{override, 'lfe-compile',
   [{deps,
     [{lfe, {git, "git://github.com/rvirding/lfe.git", {tag, "1.0"}}}]}]}]}.
```

**Comment by yurrriq** [comment]
This has an especially big impact on [Lodox](https://github.com/quasiquoting/lodox).

It turns this (LFE 0.10.1):

``` lfe
(map
 #"name"
 name
 #"tagline"
 tagline
 #"bio"
 bio
 #"image"
 image
 #"links"
 links
 #"role"
 role
 #"slug"
 slug)
```

into this (LFE 1.0):

``` lfe
(map #"name" name #"tagline" tagline #"bio" bio #"image" image
     #"links" links #"role" role #"slug" slug)
```

which in my opinion is greatly improved.

**Comment by oubiwann** [comment]
Hey man, working on this now ... you may see changing commit ids for 0.3.0, though. 

I'm seeing weird behaviours in other libs/plugins with LFE sometimes getting the right version from the compile plugin and sometimes now. Not sure what's up and trying to debug this/.

**Comment by oubiwann** [comment]
Okay, looks like an especially ellusive `rebar.lock` file tha tI finally tracked down. This commit it for 0.3.0 should stay the same, now ...

And yeah, that's _awesome_ looking! Love the new rendering of the map data. Been meaning to tell you that! :fireworks: :horse: :horse: :horse:  :rainbow: :rainbow: :rainbow:

**Comment by yurrriq** [comment]
:tada: thanks! Yeah, I think there's some sort of `rebar3 unlock` and/or `rebar3 upgrade` incantation that would help us here, but I don't grok it yet.

**Comment by yurrriq** [comment]
With that said, `overrides` work great in a pinch.
